name: Publish to PyPI

on:
    workflow_dispatch:
        inputs:
            tag_name:
                description: 'Tag name for the publish (e.g., v1.2.3)'
                required: true
                type: string
    workflow_call:
        inputs:
            tag_name:
                description: 'Tag name for the publish (e.g., v1.2.3)'
                required: true
                type: string

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
              with:
                  ref: ${{ inputs.tag_name || github.event.inputs.tag_name }}
                  fetch-depth: 0

            - name: Output build information
              run: |
                  echo "### Publishing Build :package:" >> $GITHUB_STEP_SUMMARY
                  echo "- **Version tag**: ${{ inputs.tag_name || github.event.inputs.tag_name }}" >> $GITHUB_STEP_SUMMARY

            - name: Install uv
              uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7
              with:
                  python-version: '3.14.3'
                  enable-cache: 'true'

            - name: Install dependencies
              run: uv sync --frozen

            - name: Build distribution
              run: uv build

            - name: Upload build artifacts
              uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
              with:
                  name: python-package-distributions
                  path: dist/

    publish-to-pypi:
        needs: build
        runs-on: ubuntu-latest
        environment: pypi
        permissions:
            id-token: write

        steps:
            - name: Download build artifacts
              uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7
              with:
                  name: python-package-distributions
                  path: dist/

            - name: Publish to PyPI
              uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # v1.14.0
              with:
                  packages-dir: dist/
